/* Generated by Cython 0.29.16 */

#ifndef __PYX_HAVE_API__variance_expension
#define __PYX_HAVE_API__variance_expension
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static __Pyx_memviewslice (*__pyx_api_f_18variance_expension_synthesis)(PyArrayObject *, int) = 0;
#define synthesis __pyx_api_f_18variance_expension_synthesis
static double (*__pyx_api_f_18variance_expension_erfinv_wrap)(double) = 0;
#define erfinv_wrap __pyx_api_f_18variance_expension_erfinv_wrap
static __Pyx_memviewslice (*__pyx_api_f_18variance_expension_test)(__Pyx_memviewslice) = 0;
#define test __pyx_api_f_18variance_expension_test
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_variance_expension(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("variance_expension");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "synthesis", (void (**)(void))&__pyx_api_f_18variance_expension_synthesis, "__Pyx_memviewslice (PyArrayObject *, int)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "erfinv_wrap", (void (**)(void))&__pyx_api_f_18variance_expension_erfinv_wrap, "double (double)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "test", (void (**)(void))&__pyx_api_f_18variance_expension_test, "__Pyx_memviewslice (__Pyx_memviewslice)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__variance_expension */
